config/routes.rb
Rails.application.routes.draw do


  root'items#index'

  devise_for :users

  resources :search, only: :index
  resources :notifications, only: :index


  resources :users do
    get :applying, on: :member
    get :waiting, on: :member
    get :lending, on: :member
    get :borrowing, on: :member
    get :notifications, on: :member
    get :favorite, on: :member
  end

  resources :items do
    post :apply, on: :member
    post :cancel, on: :member
    post :approve, on: :member
    post :reject, on: :member
    post :complete, on: :member
    resource :favorites, only: [:create,:destroy]
    resource :comments, only: [:create,:destroy]
  end

  get '(*unmatched_route)' => redirect('/')
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :item, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.slim
- Rails::logger::debug(notification)
- visitor = notification.visitor
- visited = notification.visited


.col-md-9.mx-auto.notifications__background
  .form-inline
    span
      - if visitor.image?
        = link_to user_path(visitor) do
          img src="#{visitor.image}" class="rounded-circle mr-1 notifications__visitor-image"
          strong
            = visitor.username
      - else
        = link_to user_path(visitor) do
          = image_tag "/images/a.png",class:'border rounded-circle mr-1 notifications__visitor-image'
          strong
            = visitor.username

      = 'さんが'
      - case notification.action
      - when 'apply' then
        = link_to "あなたの投稿「#{notification.item.tittle}」", notification.item, class:"notifications__font"
        = "に"
        = link_to "申請",waiting_user_path(current_user.id), class:"notifications__font"
        ="しました"
      - when 'cancel' then
        = link_to "あなたの投稿「#{notification.item.tittle}」", notification.item, class:"notifications__font"
        = "の申請をキャンセルしました"
      - when 'approve' then
        = link_to "あなたの投稿「#{notification.item.tittle}」", notification.item, class:"notifications__font"
        = "が"
        = link_to "承認",borrowing_user_path(current_user.id), class:"notifications__font"
        ="されました"
      - when 'reject' then
        = link_to "あなたの投稿「#{notification.item.tittle}」", notification.item, class:"notifications__font"
        = "承認"
        ="が"
        = link_to "拒否",applying_user_path(current_user.id), class:"notifications__font"
        ="されました"
      - when 'complete' then
        = link_to "あなたの投稿「#{notification.item.tittle}」", notification.item, class:"notifications__font"
        = "の返却を確認しました"
      - when 'favorite' then
        = link_to "あなたの投稿「#{notification.item.tittle}」", notification.item, class:"notifications__font"
        = "にいいねしました"
      - when 'comment' then
            - if notification.item.user_id == visited.id
              = link_to "あなたの投稿「#{notification.item.tittle}」", notification.item, class:"notifications__font"
              = "コメントしました"
            - else
              span
                = link_to item_path(notification.item)
                  strong
                    = "自身の投稿"
                ="にコメントしました"

            p.text-muted.mb-0.notifications__comments
              = simple_format Comment.find_by(id: notification.comment_id)&.content,class:"notifications__comments"
  .small.text-muted.text-right
    = time_ago_in_words(notification.created_at).upcase
  hr