config/routes.rb
Rails.application.routes.draw do


  root'items#index'

  devise_for :users

  resources :search, only: :index
  resources :notifications, only: :index


  resources :users do
    get :applying, on: :member
    get :waiting, on: :member
    get :lending, on: :member
    get :borrowing, on: :member
    get :notifications, on: :member
    get :favorite, on: :member
  end

  resources :items do
    post :apply, on: :member
    post :cancel, on: :member
    post :approve, on: :member
    post :reject, on: :member
    post :complete, on: :member
    resource :favorites, only: [:create,:destroy]
    resource :comments, only: [:create,:destroy]
  end

  get '(*unmatched_route)' => redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  mount_uploader :image, ImageUploader
  has_many :items,dependent: :destroy
  has_many :rentals
  has_many :rentals_items, through: :rentals, source: :item
  has_many :favorites
  has_many :favorite_items, through: :favorites, source: :item
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :favorite_items, through: :favorites, source: :item
  has_many :comments,dependent: :destroy

  def items
    return Item.where(user_id: self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
     @user = User.find(params[:id])
  end

  def applying
    @user = current_user
    # gemのenumerize使いたい
    # @applying_items = @user.rentals_items.where(state: :waiting)
    @applying_items = @user.rentals_items.where(state: '1')
  end

  def waiting
    @waiting_items = @user.where(state: '1')
  end

  def lending
    @lending_items = @user.where(state: '2')
  end

  def borrowing
    @borrowing_items = current_user.rentals_items.where(state: '2')
  end

  def notifications
    @notifications = current_user.passive_notifications.page(params[:page]).per(10).order(updated_at: :desc)
    # データの更新はGETではなくPOSTまたはPATCH通信で行う。
    # @notifications.where(checked: false).update_all(checked: true)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def favorite
    @user = User.find(params[:id])
    @items = @user.items
    @favorite_items = @user.favorite_items
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/applying.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
h1.mb-5.p-3 申請中一覧

- @applying_items.each_slice(4) do |items|
 card.card-deck
    - items.each do |item|
      .card.mb-4.users-card__card-size
       - if item.image?
         =link_to item
          img.bd-placeholder-img.card-img-top.users-card__card-item-img src="#{item.image}"
         h4.users-card__card-badge
           span.badge.badge-pill.badge-danger 申請中
       - else
          =link_to item
           = image_tag "/images/k.png",class:'bd-placeholder-img card-img-top users-card__card-item-img'
          h4.users-card__card-badge
            span.badge.badge-pill.badge-danger 申請中
       .card-body
         - if item.user.image?
            =link_to item.user
             img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-user-img"
         - else
           =link_to user_path(item.user.id)
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-user-img'
         h5.d-inline =link_to item.tittle, item,class:'text-dark'
         hr
         p = link_to "#{item.user.username}さんに申請中です。",item.user,class:'ml-4 d-flex justify-content-center text-dark'
         .d-flex.justify-content-center.mb-2
           - if @user.image?
             img src="#{item.rentals.last.user.image}" class='rounded-circle mb-2 mx-2 users-card__card-item-user-img'
           - else
             = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-item-user-img'
           a = "⇨"
           - if item.user.image?
             =link_to item.user
              img src="#{item.user.image}" class="rounded-circle mb-2 ml-2 users-card__card-item-user-img"
           - else
            =link_to item.user
             = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-item-user-img'

app/views/users/borrowing.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
h1.mb-5.p-3  借りている物一覧


- @borrowing_items.each_slice(4) do |items|
 card.card-deck
    - items.each do |item|
      .card.mb-4.users-card__card-size
       - if item.image?
         =link_to item
          img.bd-placeholder-img.card-img-top.users-card__card-item-img src="#{item.image}"
            h4.users-card__card-badge
             span.badge.badge-pill.badge-success 借りている
       - else
         =link_to item
          = image_tag "/images/k.png",class:'bd-placeholder-img card-img-top users-card__card-item-img'
          h4.users-card__card-badge
           span.badge.badge-pill.badge-success 借りている
       .card-body
         - if item.user.image?
            =link_to item.user
             img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-user-img"
         - else
             =link_to user_path(item.user.id)
              = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-user-img'
         h5.d-inline =link_to item.tittle, item,class:'text-dark'
         hr
         p = link_to "#{item.user.username}さんから借りています。",item.user,class:'ml-4 text-dark'
         .d-flex.justify-content-center.mb-2
          - if item.user.image?
           =link_to item.user
             img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-item-user-img"
          - else
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-item-user-img'
          a = "⇨"
          - if item.user.image?
           img src="#{item.rentals.last.user.image}" class="rounded-circle mb-2 mx-2 users-card__card-item-user-img"
          - else
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-item-user-img'

app/views/users/favorite.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
h1.mb-5.p-3 お気に入り一覧
- @favorite_items.each_slice(4) do |items|
 card.card-deck
    - items.each do |item|
      .card.mb-4.users-card__card-size
       - if item.image?
         =link_to item
           img.bd-placeholder-img.card-img-top.users-card__card-item-img src="#{item.image}"
       - else
         =link_to item
          = image_tag "/images/k.png",class:'bd-placeholder-img card-img-top users-card__card-item-img'
       - if item.state == 2
       .card-body
        - if item.user.image?
          =link_to user_path
           img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-user-img"
        - else
          =link_to user_path(item.user.id)
           = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-user-img'
        a=link_to item.tittle, item,class:'text-dark'
        - if item.favorited_by?(current_user)
            /! ログインしているユーザーがファボしたかどうかで分岐
            a.d-block
              = link_to item_favorites_path(item.id), method: :delete
               i.fas.fa-heart.card-like-icon
              a.pl-1=item.favorites.count

        .small.text-muted.text-right
          a= item.created_at.strftime('%Y/%m/%d %H:%M')

app/views/users/index.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}

- provide(:title, 'All users')


.bg-white.mx-auto.p-5.my-5.users-background
    h4.pb-5.text-center.font-weight-bold ユーザー一覧
    ul.list-unstyled.border-top
      - @users.each do |user|
        li.border-bottom.p-1
         - if user.image?
           =link_to user_path(user.id)
            img src="#{user.image}" class="rounded-circle mb-2 mr-2 users-img"
         - else
           =link_to user_path(user.id)
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-img'
         = link_to user.username, user,class:'text-dark font-weight-bold'
         p =user.self_introduction

app/views/users/lending.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
h1.mb-5.p-3  貸し出し中一覧

- @lending_items.each_slice(4) do |items|
  card.card-deck
    - items.each do |item|
      .card.mb-4.users-card__card-size
       - if item.image?
         =link_to item
          img.bd-placeholder-img.card-img-top.users-card__card-item-img src="#{item.image}"
            h4.users-card__card-badge
             span.badge.badge-pill.badge-success 貸し出し中
       - else
        =link_to item
         = image_tag "/images/k.png",class:'bd-placeholder-img card-img-top users-card__card-item-img'
         h4.users-card__card-badge
          span.badge.badge-pill.badge-success 貸し出し中
       .card-body
         - if item.user.image?
          =link_to item.user
           img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-user-img"
         - else
           =link_to user_path(item.user.id)
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-user-img'
         h5.d-inline =link_to item.tittle, item,class:'text-dark'
         hr
         p= link_to "#{item.rentals.last.user.username}さんに貸し出しています。",item.rentals.last.user,class:'ml-4 text-dark'
         .d-flex.justify-content-center.mb-2
          - if item.user.image?
             img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-item-user-img"
          - else
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-item-user-img'
          a = "⇨"
          - if item.user.image?
           =link_to item.rentals.last.user
            img src="#{item.rentals.last.user.image}" class="rounded-circle mb-2 mx-2 users-card__card-item-user-img"
          - else
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-item-user-img'
         a = link_to "返却済み",complete_item_path(item_id: item.id), method: :post,class:'button btn btn-outline-success mx-5 d-block '

app/views/users/notifications.html.slim
=render partial: 'layouts/header2',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}

- notifications = @notifications.where.not(visitor_id: current_user.id)

.bg-white.mx-auto.my-5.users-notifications-background
  h4.py-5.text-center.border-bottom.font-weight-bold 通知一覧
  - if notifications.exists?
    = render notifications
  - else
    p
      | 通知はありません

= paginate @notifications ,class:'text-center mx-auto mr-5 p-5'

app/views/users/show.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
.bg-white.mx-auto.p-5.my-5.user-show__show-background
  h4.pb-5.text-center.border-bottom.font-weight-bold プロフィール
  - if @user.image?
    img src="#{@user.image}" class="rounded-circle mb-2 mt-2 user-show__show-user-img"
  - else
    = image_tag "/images/a.png",class:'border rounded-circle mb-2 user-show__show-user-img'
  h3.d-inline.p-3.font-weight-bold =@user.username

  h3.border-bottom.mt-3 自己紹介
  p.pb-3 = simple_format @user.self_introduction,class:"users__word-wrap"

  h3.border-bottom シェア品のリクエスト
  p.pb-3 = simple_format @user.request,class:"users__word-wrap users__from"
  - if @user.id==current_user.id
   = link_to 'プロフィール変更', edit_user_registration_path(current_user.id),class:'button btn btn-outline-danger mr-3'

h1.my-5.text-center = "#{@user.username}のシェア品一覧"

- @user.items.each_slice(4) do |items|
 card.card-deck
    - items.each do |item|
      .card.mb-4.users-card__card-size
       - if item.image?
         =link_to item
           img.bd-placeholder-img.card-img-top.users-card__card-item-img src="#{item.image}"
       - else
         =link_to item
          = image_tag "/images/k.png",class:'bd-placeholder-img card-img-top users-card__card-item-img'
       - if item.state == 2
         h4.users-card__card-badge
          span.badge.badge-pill.badge-success 貸し出し中
       .card-body
        - if item.user.image?
          =link_to user_path
           img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-user-img"
        - else
          =link_to user_path(item.user.id)
           = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-user-img'
        a=link_to item.tittle, item,class:'text-dark'
        .small.text-muted.text-right
          a= item.created_at.strftime('%Y/%m/%d %H:%M')

app/views/users/waiting.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
h1.mb-5.p-3  承認待ち一覧

- @waiting_items.each_slice(4) do |items|
  card.card-deck
    - items.each do |item|
      .card.mb-4.users-card__card-size
       - if item.image?
        =link_to item
         img.bd-placeholder-img.card-img-top.users-card__card-item-img src="#{item.image}"
           h4.users-card__card-badge
            span.badge.badge-pill.badge-primary 承認待ち
       - else
         =link_to item
          = image_tag "/images/k.png",class:'bd-placeholder-img card-img-top users-card__card-item-img'
          h4.users-card__card-badge
           span.badge.badge-pill.badge-primary 承認待ち
       .card-body
         - if item.user.image?
          =link_to item.user
           img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 users-card__card-user-img"
         - else
           =link_to user_path(item.user.id)
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-user-img'
         h5.d-inline =link_to item.tittle, item,class:'text-dark'
         hr
         p = link_to "#{item.rentals.last.user.username}さんからの申請です。",item.rentals.last.user,class:'d-flex justify-content-center text-dark'
         .d-flex.justify-content-center.mb-2
          - if item.user.image?
           =link_to item.rentals.last.user
            img src="#{item.rentals.last.user.image}" class='rounded-circle mb-2 mx-2 users-card__card-item-user-img'
          - else
             =link_to item.rentals.last.user
              = image_tag "/images/a.png",class:"border rounded-circle mb-2 mr-2 users-card__card-item-user-img"
          a = "⇨"
          - if item.user.image?
             img src="#{item.user.image}" class="rounded-circle mb-2 ml-2 users-card__card-item-user-img"
          - else
            = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 users-card__card-item-user-img'
         .d-flex.justify-content-center
           a = link_to "承認する", approve_item_path(item_id: item.id), method: :post,class:'button btn btn-outline-danger mx-3 '
           a = link_to "拒否する",reject_item_path(item_id: item.id), method: :post,class:'button btn btn-outline-primary mx-3 '