config/routes.rb
Rails.application.routes.draw do


  root'items#index'

  devise_for :users

  resources :search, only: :index
  resources :notifications, only: :index


  resources :users do
    get :applying, on: :member
    get :waiting, on: :member
    get :lending, on: :member
    get :borrowing, on: :member
    get :notifications, on: :member
    get :favorite, on: :member
  end

  resources :items do
    post :apply, on: :member
    post :cancel, on: :member
    post :approve, on: :member
    post :reject, on: :member
    post :complete, on: :member
    resource :favorites, only: [:create,:destroy]
    resource :comments, only: [:create,:destroy]
  end

  get '(*unmatched_route)' => redirect('/')
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :user_id, presence: true
  validates :tittle, presence: true
  validates :share_start_date, presence: true
  validates :share_end_date, presence: true
  has_many :rentals
  has_many :notifications, dependent: :destroy
  has_many :favorites
  has_many :comments,dependent: :destroy
  belongs_to :category


  def rentaled_by?(user)
        rentals.where(user_id: user.id).exists?
  end

  def notification_comment(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(item_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      item_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  def notification_favorite(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def notification_apply(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, user_id, id, 'apply'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: user_id,
        action: 'apply'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def notification_cancel(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, user_id, id, 'cancel'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: user_id,
        action: 'cancel'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def notification_approve(current_user)
    rental = rentals.last
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, rental.user_id, id, 'approve'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: rental.user_id,
        action: 'approve'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def notification_reject(current_user)
    rental = rentals.last
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, rental.user_id, id, 'reject'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: rental.user_id,
        action: 'reject'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def notification_complete(current_user)
    rental = rentals.last
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, rental.user_id, id, 'complete'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: rental.user_id,
        action: 'complete'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index]


  def index
    @items = Item.where(state:nil)
    @items = Item.page(params[:page]).per(16).order('updated_at DESC')

  end

  def show
    @item = Item.find_by(id: params[:id])
    @comment = @item.comments.build
  end

  def new
    @item = Item.new
    @borrowing_items = current_user.rentals_items.where(state:'2')
    @waiting_items = current_user.items.where(state:'1')
  end

  def edit
    @item = current_user.items.find(params[:id])
  end

  def create
   @item = Item.new(item_params.merge(user_id: current_user.id))
   if @item.share_start_date.nil? || @item.share_end_date.nil?
     flash[:alert] = "シェア期間を入力してください"
     render :new
     return
   else
     sabun = (@item.share_start_date - Date.today).to_i
     unless sabun >= 0
       flash[:alert] = "シェア開始日は本日より以前の日付にできません"
       render :new
       return
     end
     sabun = (@item.share_end_date - @item.share_start_date).to_i
     unless sabun <= 365
       flash[:alert] = "シェア期間の最長365日間までです"
       render :new
       return
     end
     unless sabun >= 1
       flash[:alert] = "シェア終了日は本日以降の日付でお願いします"
       render :new
       return
     end
   end
   if @item.save
    redirect_to items_url,notice:"「#{@item.tittle}」をシェアしました"
   else
    @item = Item.new(item_params)
    flash[:alert] = "シェア品名を入力してください"
    render :new
    return
   end
  end

  def update
    @item = current_user.items.find(params[:id])
    @item = Item.new(item_params.merge(user_id: current_user.id))
    if @item.share_start_date.nil? || @item.share_end_date.nil?
      flash[:alert] = "シェア期間を入力してください"
      render :edit
      return
    else
      sabun = (@item.share_start_date - Date.today).to_i
      unless sabun >= 0
        flash[:alert] = "シェア開始日は本日より以前の日付にできません"
        render :edit
        return
      end
      sabun = (@item.share_end_date - @item.share_start_date).to_i
      unless sabun <= 365
        flash[:alert] = "シェア期間の最長365日間までです"
        render :edit
        return
      end
      unless sabun >= 1
        flash[:alert] = "シェア終了日は本日以降の日付でお願いします"
        render :edit
        return
      end
    end
    if @item.update(item_params)
      redirect_to items_url,notice:"シェア品「#{@item.tittle}」を更新しました"
      return
    else
      flash[:alert] = "シェア品名を入力してください"
      render :edit
      return
    end
  end

  def destroy
   item = current_user.items.find(params[:id])
   item.destroy
   redirect_to items_url,notice:"シェア品『#{item.tittle}』削除しました"
  end

  def ensure_correct_user
    @item = item.find_by(id:params[:id])
    if @item.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/items/index")
    end
  end

  def apply
    rental = current_user.rentals.build(item_id: params[:item_id])
    rental.save
    item = Item.find(params[:item_id])
    item.state = 1
    item.save!
    item_notification = Item.find(params[:item_id])
    item_notification.notification_apply(current_user)
    redirect_to items_path
  end

  def cancel
    rental = Rental.find_by(item_id: params[:item_id])
    rental.destroy
    item = Item.find(params[:item_id])
    item.state = nil
    item.save!
    item_notification = Notification.find_by(item_id: params[:item_id])
    item_notification.destroy
    item_notification_cancel = Item.find(params[:item_id])
    item_notification_cancel.notification_cancel(current_user)
    redirect_to items_path
  end

  def approve
    item = Item.find(params[:item_id])
    item.state = 2
    item.save!
    item_notification = Item.find(params[:item_id])
    item_notification.notification_approve(current_user)
    redirect_to items_path
  end

  def reject
    item_notification = Item.find(params[:item_id])
    item_notification.notification_reject(current_user)
    rental = Rental.find_by(item_id: params[:item_id])
    rental.destroy
    item = Item.find(params[:item_id])
    item.state = nil
    item.save!
    redirect_to items_path
  end

  def complete
    item_notification = Item.find(params[:item_id])
    item_notification.notification_complete(current_user)
    rental = Rental.find_by(item_id: params[:item_id])
    rental.destroy
    item = Item.find(params[:item_id])
    item.state = nil
    item.save!
    redirect_to items_path
  end



  private

  def item_params
    params.require(:item).permit(:tittle,:content,:image,:image_cache,:state,:share_start_date, :share_end_date, :category_id)
  end






end

app/helpers/items_helper.rb
module ItemsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/items/_carousel.html.slim
#carouselExampleIndicators.carousel.slide data-ride="carousel"
  ol.carousel-indicators
    li.active data-slide-to="0" data-target="#carouselExampleIndicators"
    li data-slide-to="1" data-target="#carouselExampleIndicators"
    li data-slide-to="2" data-target="#carouselExampleIndicators"
  .carousel-inner
    .carousel-item.active
      svg.bd-placeholder-img.bd-placeholder-img-lg.d-block.w-100 aria-label=("Placeholder: First slide") focusable="false" height="400" preserveaspectratio=("xMidYMid slice") role="img" width="800" xmlns="http://www.w3.org/2000/svg"

    .carousel-item
      svg.bd-placeholder-img.bd-placeholder-img-lg.d-block.w-100 aria-label=("Placeholder: Second slide") focusable="false" height="400" preserveaspectratio=("xMidYMid slice") role="img" width="800" xmlns="http://www.w3.org/2000/svg"

    .carousel-item
      svg.bd-placeholder-img.bd-placeholder-img-lg.d-block.w-100 aria-label=("Placeholder: Third slide") focusable="false" height="400" preserveaspectratio=("xMidYMid slice") role="img" width="800" xmlns="http://www.w3.org/2000/svg"
        
  a.carousel-control-prev data-slide="prev" href="#carouselExampleIndicators" role="button"
    span.carousel-control-prev-icon aria-hidden="true"
    span.sr-only Previous
  a.carousel-control-next data-slide="next" href="#carouselExampleIndicators" role="button"
    span.carousel-control-next-icon aria-hidden="true"
    span.sr-only Next

app/views/items/edit.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}

.text-center.bg-white.mx-auto.my-5.items__background
  h4.mx-auto.py-5.border-bottom.font-weight-bold シェア情報を入力
  - if notice
    =notice
  -if alert
   .alert.alert-danger.text-center.mx-auto.font-weight-bold.mt-3.items__alert
    =alert
  - if @item.image?
   = image_tag @item.image.url,class: 'item__image'
  - else
    = image_tag "/images/k.png",class:'item__image'

  = form_with model:@item,local:true do |f|
    = f.label "画像を変更",class:"pt-3"
    br/
    = f.file_field :image,class:"border rounded p-5 "
    .form-group.mt-5
      a.mr-1 シェア品名
      .items__badge
        .badge.badge-danger 必須
      =f.text_field :tittle,class: 'form-control mx-auto m-2',id: 'task_tittle',id: 'task_tittle'
    .form-group.my-5
      =f.label :商品説明
      =f.text_area :content,row:5, class: 'form-control mx-auto mb-4',id: 'task_content item__textarea'
      = f.select :category_id, Category.all.pluck(:name, :id), {}, class: 'form-control', prompt: "カテゴリを選択"
      br
      a.mr-1 シェア開始日
      .items__badge
       .badge.badge-danger 必須
       .form-inline.d-flex.justify-content-center.m-2
        = date_field_tag 'item[share_start_date]', nil,class: 'form-control',id: 'task_share_start_date'
      a.mr-1 シェア終了日
      .items__badge
       .badge.badge-danger 必須
      .form-inline.d-flex.justify-content-center.m-2
        = date_field_tag 'item[share_end_date]', nil,class: 'form-control ',id: 'task_share_end_date'
    =f.submit nil,class: 'btn btn-primary mt-3 mb-5 item__submit'

app/views/items/index.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
=render partial: 'partial/carousel'
p デプロイテスト
- if notice
 .alert.alert-secondary.text-center.mx-auto.font-weight-bold.mt-3.items__notice role="notice"
  =notice
-if alert
 .alert.alert-secondary.text-center.mx-auto.font-weight-bold.mt-3.alert__style.items__alert role="notice"
  =alert
h2.pb-4.pt-3.d-flex.justify-content-center.bg-white.items__title  シェア一覧
- @searchs.each_slice(4) do |items|
 card.card-deck.items-card
   - items.each do |item|
      br
         .card.mb-4.items-card__card-size
          - if item.image?
            .items-card__imgWrap
              =link_to item
                = image_tag item.image.url,class:"bd-placeholder-img card-img-top items-card__card-item-img"
          - else
            .items-card__imgWrap
               =link_to item
                = image_tag "/images/k.png",class:'bd-placeholder-img card-img-top items-card__card-item-img'
          .card-body
             - if item.user.image?
               =link_to user_path(item.user.id)
                img src="#{item.user.image}" class="rounded-circle mb-2 mr-2 items-card__card-user-img"
             - else
               =link_to user_path(item.user.id)
                = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 items-card__card-user-img'

             a=link_to item.tittle, item,class:'text-dark text-center'
             - if user_signed_in?
               - if item.favorited_by?(current_user)
                 a.d-block
                   = link_to item_favorites_path(item.id), method: :delete
                    i.fas.fa-heart.pl-1.items-card__card-like-icon
                   a.pl-1 = item.favorites.count
               - else
                 a.d-block
                   a= link_to item_favorites_path(item.id), method: :post
                    i.far.fa-heart.pl-1.items-card__card-unlike-icon
                   a.pl-1= item.favorites.count
             - else
                 a.d-block
                   a
                    i.far.fa-heart.pl-1.items-card__card-unlike-icon
                   a.pl-1= item.favorites.count
             .small.text-muted.text-right
               a= item.created_at.strftime('%Y/%m/%d %H:%M')


= paginate @items

app/views/items/new.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
.text-center.bg-white.mx-auto.my-5.items__background
  h4.mx-auto.py-5.border-bottom.font-weight-bold シェア情報を入力

  - if notice
    =notice
  -if alert
   .alert.alert-danger.text-center.mx-auto.font-weight-bold.mt-3.items__alert
    =alert

  = form_with model:@item,local:true do |f|
    = image_tag @item.image.url,class:' rounded shadow mx-auto item__image' if @item.image.present?
    = f.label "画像をアップロード" ,class:"pt-4 d-block"
    br/
    = f.file_field :image,class: "border rounded p-5 "
    = f.hidden_field :image_cache
    .form-group.mt-5
      =f.label :シェア品名
      .items__badge
        .badge.badge-danger.m-2 必須
      =f.text_field :tittle,class: 'form-control mx-auto',id: 'task_tittle'
    .form-group.my-5
      =f.label :商品説明
      =f.text_area :content,class: 'form-control mx-auto mb-4',id: 'task_content'
    .form-group
      .select
        = f.label :category_id
        = f.select :category_id, Category.all.pluck(:name, :id),{prompt: "カテゴリを選択"},class: 'form-control select'
      br
      a.mr-1 シェア開始日
      .items__badge
        .badge.badge-danger 必須
      .form-inline.d-flex.justify-content-center.m-2
        = f.date_field 'share_start_date',class: 'form-control',type:"date",id: 'task_share_start_date'
      a.mr-1 シェア終了日
      .items__badge
        .badge.badge-danger 必須
      .form-inline.d-flex.justify-content-center.m-2
        = f.date_field 'share_end_date',class: 'form-control',id: 'task_share_end_date'
    =f.submit nil,class: 'btn btn-danger mt-3 mb-5 item__submit'

app/views/items/show.html.slim
=render partial: 'layouts/header',locals:{item:@item,borrowing_items:@borrowing_items,waiting_items:@waiting_items,applying_items:@applying_items,lending_items:@lending_items}
.bg-white.mx-auto.mb-3.mt-5.pt-3.items__background

  
  h2.font-weight-bold.mb-3.text-center = @item.tittle
  .text-center
    - if @item.image?
     = image_tag @item.image.url,class:'my-3 rounded shadow mx-auto item__image'
    - else
     = image_tag "/images/k.png",class:'rounded shadow mx-auto item__image'
  .text-center.mt-3
   .badge.badge-success.mr-1 シェア期間
   a.mx-1= @item.share_start_date.strftime('%Y年%m月%d日')
   a 〜
   a.mx-1= @item.share_end_date.strftime('%Y年%m月%d日')
  p.p-4.mx-5.text-left= simple_format @item.content,class:"items__comments"

  .text-center
    - if user_signed_in? && @item.user_id==current_user.id && @item.state == nil
     p.mx-2.my-3
       = link_to '編集',edit_item_path,class: 'btn btn-outline-primary mr-3'
       = link_to '削除',@item,method: :delete, remote:true , data:{ confirm:"タスク「#{@item.tittle}」を削除します。よろしいですか？"}, class: 'btn btn-outline-danger'
    - if current_user != @item.user
     -if @item.state != 2
      - if @item.rentaled_by?(current_user)
       p = link_to "申請をキャンセルする",cancel_item_path(item_id: @item.id), method: :post,class:'button btn btn-outline-primary mx-3 my-3 '
      - else
       p = link_to "申請する",apply_item_path(item_id: @item.id), method: :post,class:'button btn btn-outline-danger mx-3 my-3 '

  - if @item.user.image?
    a=link_to user_path(@item.user.id)
     img src="#{@item.user.image}" class="rounded-circle mb-2 mr-2 item__user__img"
  - else
    a=link_to user_path(@item.user.id)
      = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 item__user__img'
  h5.d-inline.mr-4= link_to @item.user.username, "/users/#{@item.user_id}" ,class:'text-dark'

  - if user_signed_in?
     - if @item.favorited_by?(current_user)
       a
         = link_to item_favorites_path(@item.id), method: :delete
          i.fas.fa-heart.items-card__card-like-icon
         a.pl-1= @item.favorites.count
         a.mx-1 いいね済み
     - else
       a
         = link_to item_favorites_path(@item.id), method: :post
          i.far.fa-heart.items-card__card-unlike-icon
         a.pl-1 = @item.favorites.count
         a.mx-1 件のいいね
  - else
      p
       i.far.fa-heart.items-card__card-unlike-icon
       = item.favorites.count
  
  a.ml-2 カテゴリー:#{@item.category.name}

.comment-wrapper class=" mx-auto my-2 items__background"
 p.border-bottom コメント一覧
 - @item.comments.each do |c|
   - unless c.user.blank?
     - if c.user.image?
       a=link_to user_path(c.user.id)
        img src="#{c.user.image}" class="rounded-circle mb-2 mr-2 items-comments__comments-user-imag"
     - else
       a=link_to user_path(c.user.id)
         = image_tag "/images/a.png",class:'border rounded-circle mb-2 mr-2 items-comments__comments-user-imag'
     a.font-weight-bold= c.user.username
     p= simple_format c.content,class:"items__comments"
     - if current_user == c.user
      = link_to "削除", item_comments_path(@comment.item_id, @comment.id), method: :delete,class:"badge badge-danger mb-1"
     hr class="my-0"
 - if user_signed_in?
   = form_with(model: [@item, @comment], local: true) do |f|
     = f.text_area :content, class: "form-control", rows: 5
     = button_tag type: "submit", class: "btn btn-success float-right mt-2 mb-3" do
       i.far.fa-comments
       | コメントする