config/routes.rb
Rails.application.routes.draw do


  root'items#index'

  devise_for :users

  resources :search, only: :index
  resources :notifications, only: :index


  resources :users do
    get :applying, on: :member
    get :waiting, on: :member
    get :lending, on: :member
    get :borrowing, on: :member
    get :notifications, on: :member
    get :favorite, on: :member
  end

  resources :items do
    post :apply, on: :member
    post :cancel, on: :member
    post :approve, on: :member
    post :reject, on: :member
    post :complete, on: :member
    resource :favorites, only: [:create,:destroy]
    resource :comments, only: [:create,:destroy]
  end

  get '(*unmatched_route)' => redirect('/')
end

app/views/layouts/_footer.html.slim
footer
 nav.navbar.navbar-expand-lg.navbar-light.bg-light.border-0.p-5
  a.navbar-brand href="#"  Navbar
  button.navbar-toggler aria-controls="navbarNav" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNav" data-toggle="collapse" type="button"
   span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse.justify-content-around
    ul.navbar-nav
     li.nav-item.mr-5.mr-5
      a.nav-link href="#"
       | Home
       span.sr-only (current)
     li.nav-item.mr-5.mr-5
      a.nav-link href="#"  Features
     li.nav-item.mr-5.mr-5
      a.nav-link href="#"  Pricing
     li.nav-item.mr-5.mr-5
      a.nav-link href="#"  Disabled

app/views/layouts/_header.html.slim
headr
.shadow.pt-2.pb-3.px-3.mb-0.bg-white.rounded
 nav.navbar.navbar-light.bg-white.d-flex.justify-content-center
  = link_to "/"
   = image_tag "/images/logo.png",class:'rounded-circle mb-2 header__logo'
   a.navbar-brand.font-weight-bold href="/" MONOシェア
  = search_form_for @search, url: search_index_path do |f|
    .form-inline
     = f.text_field :tittle_cont, class: "form-control ", placeholder: '何かお探しですか？'
     = f.select :category_id_eq, Category.all.pluck(:name, :id), { include_blank: 'カテゴリを選択' }, class: "form-control mr-sm-2"
     = f.submit '検索',class:'button btn btn-outline-success'
 .d-flex.justify-content-end.mr-5.header-color

  - if user_signed_in?
    = link_to "/",class:"header-color"
     i.fas.fa-home.fa-lg.pt-1
    = link_to 'ホームに戻る', "/",class:"p-1 mr-4 text-dark header-color"
    = link_to new_item_path,class:"header-color"
     i.far.fa-handshake.fa-lg.pt-2
    = link_to 'シェアする', new_item_path,class:"p-1 mr-4 text-dark header-color"

    i.far.fa-file-alt.fa-lg.pt-2 class="header-color"
    .nav-item.dropdown
       a.nav-link.dropdown-toggle.p-1.mr-3.text-dark aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"  一覧リスト
       .dropdown-menu.text-center
         a.dropdown-item

         = link_to 'ユーザー一覧', users_path,class:"text-dark"
         a.dropdown-item

         = link_to 'お気に入り一覧', favorite_user_path(current_user.id),class:"text-dark"
         a.dropdown-item

         = link_to '申請中一覧',  applying_user_path(current_user.id),class:"text-dark "
         -if applying_items.count != 0
           a.rounded-circle.dropdown-menu__menu-1
             =applying_items.count
         a.dropdown-item

         = link_to '承認待ち一覧', waiting_user_path(current_user.id),class:"text-dark "
         -if  waiting_items.count != 0
           a.rounded-circle.dropdown-menu__menu-2
             =waiting_items.count
         a.dropdown-item

         = link_to '貸し出し中一覧', lending_user_path(current_user.id),class:"text-dark "
         -if lending_items.count != 0
           a.rounded-circle.dropdown-menu__menu-3
             =lending_items.count
         a.dropdown-item

         = link_to '借りている物一覧', borrowing_user_path(current_user.id),class:"text-dark"
         -if borrowing_items.count != 0
           a.rounded-circle.dropdown-menu__menu-4
            =borrowing_items.count
    - if unchecked_notifications.any?
     i.far.fa-bell.fa-lg.pt-2.mr-1.header-notifications__icn-unchecked
    - else
     i.far.fa-bell.fa-lg.pt-2.mr-1.header-notifications__icn-checked
    - if unchecked_notifications.any?
       a = link_to "通知一覧",notifications_user_path(current_user.id),class:"p-1 mr-4 header-notifications__unchecked",id:"通知一覧"
    - else
       a = link_to "通知一覧",notifications_user_path(current_user.id),class:"p-1 mr-4 text-dark header-notifications__checked",id:"通知一覧"

    - if current_user.image?
      = link_to user_path(current_user.id)
       img src="#{current_user.image}" class="rounded-circle header-user-img"
    - else
      = link_to user_path(current_user.id)
       = image_tag "/images/a.png",class:'border rounded-circle header-user-img'
    .nav-item.dropdown
        a.nav-link.dropdown-toggle.p-1.text-dark.header-color aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" マイページ
        .dropdown-menu.text-center
          a.dropdown-item = link_to "プロフィール", user_path(current_user.id),class:"text-dark"
          a.dropdown-item = link_to 'ログアウト', destroy_user_session_path, method: :delete,class:"text-dark"

  - else
    = link_to '新規登録', new_user_registration_path,class:'button btn btn-outline-danger mr-3 '
    = link_to 'ログイン', new_user_session_path,class:'button btn btn-outline-primary '

app/views/layouts/_header2.html.slim
headr
.shadow.pt-2.pb-3.px-3.mb-0.bg-white.rounded
 nav.navbar.navbar-light.bg-white.d-flex.justify-content-center
  = link_to "/"
   = image_tag "/images/logo.png",class:'rounded-circle mb-2 header__logo'
  a.navbar-brand.font-weight-bold href="/" MONOシェア
  = search_form_for @search, url: search_index_path do |f|
    .form-inline
     = f.text_field :tittle_cont, class: "form-control mr-sm-2 ", placeholder: '何かお探しですか？'
     = f.submit '検索',class:'button btn btn-outline-success'
 .d-flex.justify-content-end.mr-5.header-color

  - if user_signed_in?
    = link_to "/",class:"header-color"
     i.fas.fa-home.fa-lg.pt-1
    = link_to 'ホームに戻る', "/",class:"p-1 mr-4 text-dark header-color"
    = link_to new_item_path,class:"header-color"
     i.far.fa-handshake.fa-lg.pt-2.mr-1
    = link_to 'シェアする', new_item_path,class:"p-1 mr-4 text-dark header-color"

    i.far.fa-file-alt.fa-lg.pt-2.mr-1 class="header-color"
    .nav-item.dropdown
       a.nav-link.dropdown-toggle.p-1.mr-3.text-dark aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"  一覧リスト
       .dropdown-menu.text-center
         a.dropdown-item

         = link_to 'ユーザー一覧', users_path,class:"text-dark"
         a.dropdown-item

         = link_to 'お気に入り一覧', favorite_user_path(current_user.id),class:"text-dark"
         a.dropdown-item

         = link_to '申請中一覧',  applying_user_path(current_user.id),class:"text-dark "
         -if applying_items.count != 0
           a.rounded-circle.dropdown-menu__menu-1
             =applying_items.count
         a.dropdown-item

         = link_to '承認待ち一覧', waiting_user_path(current_user.id),class:"text-dark "
         -if  waiting_items.count != 0
           a.rounded-circle.dropdown-menu__menu-2
             =waiting_items.count
         a.dropdown-item

         = link_to '貸し出し中一覧', lending_user_path(current_user.id),class:"text-dark "
         -if lending_items.count != 0
           a.rounded-circle.dropdown-menu__menu-3
             =lending_items.count
         a.dropdown-item

         = link_to '借りている物一覧', borrowing_user_path(current_user.id),class:"text-dark "
         -if borrowing_items.count != 0
           a.rounded-circle.dropdown-menu__menu-4
             =borrowing_items.count

    - if current_user.image?
      = link_to user_path(current_user.id)
       img src="#{current_user.image}" class="rounded-circle header-user-img"
    - else
      = link_to user_path(current_user.id)
       = image_tag "/images/a.png",class:'border  rounded-circle header-user-img'

    .nav-item.dropdown
        a.nav-link.dropdown-toggle.p-1.text-dark.header-color aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" style="color:#6c757d;" マイページ
        .dropdown-menu.text-center
          a.dropdown-item = link_to "プロフィール", user_path(current_user.id),class:"text-dark"
          a.dropdown-item = link_to 'ログアウト', destroy_user_session_path, method: :delete,class:"text-dark"

  - else
    = link_to 'サインアップ', new_user_registration_path,class:'button btn btn-outline-danger mr-3 '
    = link_to 'ログイン', new_user_session_path,class:'button btn btn-outline-primary '

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Monoshare
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    script crossorigin="anonymous" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    script crossorigin="anonymous" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    script crossorigin="anonymous" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    
    link href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" rel="stylesheet" /

    <!-- BootstrapCDN -->
    link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/litera/bootstrap.min.css" integrity="sha384-D/7uAka7uwterkSxa2LwZR7RJqH2X6jfmhkJ0vFPGUtPyBMF2WMq9S+f9Ik5jJu1" rel="stylesheet" /


  body




    = yield